# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

title: "Jared Lutteke"
subtitle: "Whatever comes to mind!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaredlutteke.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.21.0" 
plugins:
  - jekyll-feed
  - jekyll-include-cache

footer:
    links:
        - label: "GitHub"
          icon: "fab fa-fw fa-github"
          url: "https://github.com/raffledoocious"
